import { LanguageName, LanguageNativeName } from './types';

const LANGUAGES_TO_NATIVES = {
    'Acehnese': 'Bahsa Acèh',
    'Afrikaans': 'Afrikaans',
    'Akan': 'Akan',
    'Albanian': 'Shqip',
    'Amharic': 'አማርኛ',
    'Arabic': 'العربية',
    'Armenian': 'Հայերեն',
    'Assamese': 'অসমীয়া',
    'Awadhi': 'अवधी',
    'Aymara': 'Aymar aru',
    'Azerbaijani': 'Azərbaycan',
    'Balinese': 'Basa Bali',
    'Balochi': 'بلوچی',
    'Bambara': 'Bamanankan',
    'Banjar': 'Bahasa Banjar',
    'Bashkir': 'Башҡорт теле',
    'Basque': 'Euskara',
    'Batak': 'Hata Batak',
    'Belarusian': 'Беларуская',
    'Bemba': 'Ichibemba',
    'Bengali': 'বাংলা',
    'Bhojpuri': 'भोजपुरी',
    'Bikol': 'Bikol',
    'Bosnian': 'Bosanski',
    'Breton': 'Brezhoneg',
    'Buginese': 'Basa Ugi',
    'Bulgarian': 'Български',
    'Burmese': 'မြန်မာဘာသာ',
    'Cantonese': '粵語',
    'Catalan': 'Català',
    'Cebuano': 'Sinugbuanong Binisaya',
    'Chhattisgarhi': 'छत्तिसगढ़ी',
    'Chewa': 'Chichewa',
    'Chinese': '中文',
    'Chittagonian': 'চাটগাঁইয়া',
    'Chuvash': 'Чӑваш чӗлхи',
    'Corsican': 'Corsu',
    'Cree': 'Nēhiyawēwin',
    'Croatian': 'Hrvatski',
    'Czech': 'Čeština',
    'Danish': 'Dansk',
    'Dari': 'دری',
    'Dholuo': 'Dholuo',
    'Dutch': 'Nederlands',
    'Dzongkha': 'རྫོང་ཁ',
    'English': 'English',
    'Esperanto': 'Esperanto',
    'Estonian': 'Eesti',
    'Ewe': 'Eʋegbe',
    'Faroese': 'Føroyskt',
    'Fijian': 'Na Vosa Vakaviti',
    'Filipino': 'Filipino',
    'Finnish': 'Suomi',
    'French': 'Français',
    'Frisian': 'Frysk',
    'Fulani': 'Fulfulde',
    'Ga': 'Ga',
    'Galician': 'Galego',
    'Gan': '贛語',
    'Garhwali': 'गढ़वाली',
    'Georgian': 'ქართული',
    'German': 'Deutsch',
    'Gondi': 'Gondi',
    'Greek': 'Ελληνικά',
    'Guarani': "Avañe'ẽ",
    'Gujarati': 'ગુજરાતી',
    'Haitian Creole': 'Kreyòl ayisyen',
    'Hakka': '客家話',
    'Haryanvi': 'हरियाणवी',
    'Hausa': 'Hausa',
    'Hawaiian': "ʻŌlelo Hawaiʻi",
    'Hebrew': 'עברית',
    'Hiligaynon': 'Hiligaynon',
    'Hindi': 'हिन्दी',
    'Hmong': 'Hmoob',
    'Hungarian': 'Magyar',
    'Icelandic': 'Íslenska',
    'Igbo': 'Igbo',
    'Ilocano': 'Ilokano',
    'Indonesian': 'Bahasa Indonesia',
    'Inuktitut': 'ᐃᓄᒃᑎᑐᑦ',
    'Irish': 'Gaeilge',
    'Italian': 'Italiano',
    'Japanese': '日本語',
    'Javanese': 'Basa Jawa',
    'Kabyle': 'Taqbaylit',
    'Kamba': 'Kikamba',
    'Kannada': 'ಕನ್ನಡ',
    'Kanuri': 'Kanuri',
    'Kapampangan': 'Kapampangan',
    'Karen': 'ကညီကျိာ်',
    'Kashmiri': 'कश्मीरी',
    'Kashubian': 'Kaszëbsczi',
    'Kazakh': 'Қазақ тілі',
    'Khmer': 'ភាសាខ្មែរ',
    'Kikuyu': 'Gĩkũyũ',
    'Kinyarwanda': 'Ikinyarwanda',
    'Kirundi': 'Ikirundi',
    'Komi': 'Коми кыв',
    'Konkani': 'कोंकणी',
    'Korean': '한국어',
    'Kurdish': 'Kurdî',
    'Kurmanji': 'Kurmancî',
    'Kyrgyz': 'Кыргызча',
    'Lao': 'ພາສາລາວ',
    'Latin': 'Latina',
    'Latvian': 'Latviešu',
    'Ligurian': 'Ligure',
    'Limburgish': 'Limburgs',
    'Lingala': 'Lingála',
    'Lithuanian': 'Lietuvių',
    'Lombard': 'Lombard',
    'Luba-Kasai': 'Tshiluba',
    'Luganda': 'Luganda',
    'Luo': 'Luo',
    'Luxembourgish': 'Lëtzebuergesch',
    'Macedonian': 'Македонски',
    'Madurese': 'Basa Madura',
    'Magahi': 'मगही',
    'Maithili': 'मैथिली',
    'Makassar': 'Basa Mangkasara',
    'Malagasy': 'Malagasy',
    'Malay': 'Bahasa Melayu',
    'Malayalam': 'മലയാളം',
    'Maltese': 'Malti',
    'Mandarin': '官話',
    'Manipuri': 'মনিপুরি',
    'Maori': 'Te Reo Māori',
    'Mapudungun': 'Mapudungun',
    'Maranao': 'Mëranaw',
    'Marathi': 'मराठी',
    'Marwari': 'मारवाड़ी',
    'Maya': "Maaya T'aan",
    'Meitei': 'ꯃꯩꯇꯩꯂꯣꯟ',
    'Meru': 'Kĩmĩrũ',
    'Min Nan': '閩南語',
    'Minangkabau': 'Baso Minangkabau',
    'Mirandese': 'Mirandés',
    'Mixtec': "Tu'un savi",
    'Mon': 'ဘာသာ မန်',
    'Mongolian': 'Монгол',
    'Montenegrin': 'Crnogorski',
    'Mossi': 'Mòoré',
    'Nahuatl': 'Nāhuatl',
    'Navajo': 'Diné bizaad',
    'Nepali': 'नेपाली',
    'Newar': 'नेपाल भाषा',
    'Norwegian': 'Norsk',
    'Nyanja': 'Chinyanja',
    'Occitan': 'Occitan',
    'Odia': 'ଓଡ଼ିଆ',
    'Ojibwe': 'Anishinaabemowin',
    'Oromo': 'Afaan Oromoo',
    'Pangasinan': 'Pangasinan',
    'Pashto': 'پښتو',
    'Persian': 'فارسی',
    'Polish': 'Polski',
    'Portuguese': 'Português',
    'Punjabi': 'ਪੰਜਾਬੀ',
    'Quechua': 'Runa Simi',
    'Rajasthani': 'राजस्थानी',
    'Rohingya': 'Ruáinga',
    'Romani': 'Romani',
    'Romanian': 'Română',
    'Romansh': 'Rumantsch',
    'Russian': 'Русский',
    'Samoan': 'Gagana Samoa',
    'Sango': 'Sängö',
    'Sanskrit': 'संस्कृतम्',
    'Santali': 'संथाली',
    'Sardinian': 'Sardu',
    'Scots': 'Scots',
    'Serbian': 'Српски',
    'Sesotho': 'Sesotho',
    'Shan': 'ၵႂၢမ်းတႆး',
    'Shona': 'chiShona',
    'Sicilian': 'Sicilianu',
    'Silesian': 'Ślōnskŏ gŏdka',
    'Sindhi': 'سنڌي',
    'Sinhala': 'සිංහල',
    'Slovak': 'Slovenčina',
    'Slovenian': 'Slovenščina',
    'Somali': 'Af-Soomaali',
    'Soninke': 'Soninke',
    'Sorani': 'سۆرانی',
    'Spanish': 'Español',
    'Sundanese': 'Basa Sunda',
    'Swahili': 'Kiswahili',
    'Swati': 'SiSwati',
    'Swedish': 'Svenska',
    'Sylheti': 'ꠍꠤꠟꠐꠤ',
    'Tagalog': 'Tagalog',
    'Tahitian': 'Reo Tahiti',
    'Tajik': 'Тоҷикӣ',
    'Tamil': 'தமிழ்',
    'Tatar': 'Татарча',
    'Telugu': 'తెలుగు',
    'Tetum': 'Tetun',
    'Thai': 'ไทย',
    'Tibetan': 'བོད་ཡིག',
    'Tigrinya': 'ትግርኛ',
    'Tongan': 'Lea faka-Tonga',
    'Tsonga': 'Xitsonga',
    'Tswana': 'Setswana',
    'Tumbuka': 'chiTumbuka',
    'Turkish': 'Türkçe',
    'Turkmen': 'Türkmençe',
    'Tuvalu': 'Te gana Tuvalu',
    'Twi': 'Twi',
    'Udmurt': 'Удмурт',
    'Ukrainian': 'Українська',
    'Urdu': 'اردو',
    'Uyghur': 'ئۇيغۇرچە',
    'Uzbek': "O'zbek",
    'Valencian': 'Valencià',
    'Venda': 'Tshivenḓa',
    'Venetian': 'Vèneto',
    'Vietnamese': 'Tiếng Việt',
    'Waray': 'Winaray',
    'Welsh': 'Cymraeg',
    'Wolof': 'Wolof',
    'Wu': '吳語',
    'Xhosa': 'isiXhosa',
    'Xiang': '湘語',
    'Yakut': 'Саха тыла',
    'Yao': 'Chiyao',
    'Yiddish': 'ייִדיש',
    'Yoruba': 'Yorùbá',
    'Yucatec Maya': "Yucatec Maaya T'aan",
    'Zapotec': 'Diidxazá',
    'Zhuang': 'Vahcuengh',
    'Zulu': 'isiZulu',
} as const;

const NATIVES_TO_LANGUAGES = {
    'Bahsa Acèh': 'Acehnese',
    'Afrikaans': 'Afrikaans',
    'Akan': 'Akan',
    'Shqip': 'Albanian',
    'አማርኛ': 'Amharic',
    'العربية': 'Arabic',
    'Հայերեն': 'Armenian',
    'অসমীয়া': 'Assamese',
    'अवधी': 'Awadhi',
    'Aymar aru': 'Aymara',
    'Azərbaycan': 'Azerbaijani',
    'Basa Bali': 'Balinese',
    'بلوچی': 'Balochi',
    'Bamanankan': 'Bambara',
    'Bahasa Banjar': 'Banjar',
    'Башҡорт теле': 'Bashkir',
    'Euskara': 'Basque',
    'Hata Batak': 'Batak',
    'Беларуская': 'Belarusian',
    'Ichibemba': 'Bemba',
    'বাংলা': 'Bengali',
    'भोजपुरी': 'Bhojpuri',
    'Bikol': 'Bikol',
    'Bosanski': 'Bosnian',
    'Brezhoneg': 'Breton',
    'Basa Ugi': 'Buginese',
    'Български': 'Bulgarian',
    'မြန်မာဘာသာ': 'Burmese',
    '粵語': 'Cantonese',
    'Català': 'Catalan',
    'Sinugbuanong Binisaya': 'Cebuano',
    'छत्तिसगढ़ी': 'Chhattisgarhi',
    'Chichewa': 'Chewa',
    '中文': 'Chinese',
    'চাটগাঁইয়া': 'Chittagonian',
    'Чӑваш чӗлхи': 'Chuvash',
    'Corsu': 'Corsican',
    'Nēhiyawēwin': 'Cree',
    'Hrvatski': 'Croatian',
    'Čeština': 'Czech',
    'Dansk': 'Danish',
    'دری': 'Dari',
    'Dholuo': 'Dholuo',
    'Nederlands': 'Dutch',
    'རྫོང་ཁ': 'Dzongkha',
    'English': 'English',
    'Esperanto': 'Esperanto',
    'Eesti': 'Estonian',
    'Eʋegbe': 'Ewe',
    'Føroyskt': 'Faroese',
    'Na Vosa Vakaviti': 'Fijian',
    'Filipino': 'Filipino',
    'Suomi': 'Finnish',
    'Français': 'French',
    'Frysk': 'Frisian',
    'Fulfulde': 'Fulani',
    'Ga': 'Ga',
    'Galego': 'Galician',
    '贛語': 'Gan',
    'गढ़वाली': 'Garhwali',
    'ქართული': 'Georgian',
    'Deutsch': 'German',
    'Gondi': 'Gondi',
    'Ελληνικά': 'Greek',
    "Avañe'ẽ": 'Guarani',
    'ગુજરાતી': 'Gujarati',
    'Kreyòl ayisyen': 'Haitian Creole',
    '客家話': 'Hakka',
    'हरियाणवी': 'Haryanvi',
    'Hausa': 'Hausa',
    "ʻŌlelo Hawaiʻi": 'Hawaiian',
    'עברית': 'Hebrew',
    'Hiligaynon': 'Hiligaynon',
    'हिन्दी': 'Hindi',
    'Hmoob': 'Hmong',
    'Magyar': 'Hungarian',
    'Íslenska': 'Icelandic',
    'Igbo': 'Igbo',
    'Ilokano': 'Ilocano',
    'Bahasa Indonesia': 'Indonesian',
    'ᐃᓄᒃᑎᑐᑦ': 'Inuktitut',
    'Gaeilge': 'Irish',
    'Italiano': 'Italian',
    '日本語': 'Japanese',
    'Basa Jawa': 'Javanese',
    'Taqbaylit': 'Kabyle',
    'Kikamba': 'Kamba',
    'ಕನ್ನಡ': 'Kannada',
    'Kanuri': 'Kanuri',
    'Kapampangan': 'Kapampangan',
    'ကညီကျိာ်': 'Karen',
    'कश्मीरी': 'Kashmiri',
    'Kaszëbsczi': 'Kashubian',
    'Қазақ тілі': 'Kazakh',
    'ភាសាខ្មែរ': 'Khmer',
    'Gĩkũyũ': 'Kikuyu',
    'Ikinyarwanda': 'Kinyarwanda',
    'Ikirundi': 'Kirundi',
    'Коми кыв': 'Komi',
    'कोंकणी': 'Konkani',
    '한국어': 'Korean',
    'Kurdî': 'Kurdish',
    'Kurmancî': 'Kurmanji',
    'Кыргызча': 'Kyrgyz',
    'ພາສາລາວ': 'Lao',
    'Latina': 'Latin',
    'Latviešu': 'Latvian',
    'Ligure': 'Ligurian',
    'Limburgs': 'Limburgish',
    'Lingála': 'Lingala',
    'Lietuvių': 'Lithuanian',
    'Lombard': 'Lombard',
    'Tshiluba': 'Luba-Kasai',
    'Luganda': 'Luganda',
    'Luo': 'Luo',
    'Lëtzebuergesch': 'Luxembourgish',
    'Македонски': 'Macedonian',
    'Basa Madura': 'Madurese',
    'मगही': 'Magahi',
    'मैथिली': 'Maithili',
    'Basa Mangkasara': 'Makassar',
    'Malagasy': 'Malagasy',
    'Bahasa Melayu': 'Malay',
    'മലയാളം': 'Malayalam',
    'Malti': 'Maltese',
    '官話': 'Mandarin',
    'মনিপুরি': 'Manipuri',
    'Te Reo Māori': 'Maori',
    'Mapudungun': 'Mapudungun',
    'Mëranaw': 'Maranao',
    'मराठी': 'Marathi',
    'मारवाड़ी': 'Marwari',
    "Maaya T'aan": 'Maya',
    'ꯃꯩꯇꯩꯂꯣꯟ': 'Meitei',
    'Kĩmĩrũ': 'Meru',
    '閩南語': 'Min Nan',
    'Baso Minangkabau': 'Minangkabau',
    'Mirandés': 'Mirandese',
    "Tu'un savi": 'Mixtec',
    'ဘာသာ မန်': 'Mon',
    'Монгол': 'Mongolian',
    'Crnogorski': 'Montenegrin',
    'Mòoré': 'Mossi',
    'Nāhuatl': 'Nahuatl',
    'Diné bizaad': 'Navajo',
    'नेपाली': 'Nepali',
    'नेपाल भाषा': 'Newar',
    'Norsk': 'Norwegian',
    'Chinyanja': 'Nyanja',
    'Occitan': 'Occitan',
    'ଓଡ଼ିଆ': 'Odia',
    'Anishinaabemowin': 'Ojibwe',
    'Afaan Oromoo': 'Oromo',
    'Pangasinan': 'Pangasinan',
    'پښتو': 'Pashto',
    'فارسی': 'Persian',
    'Polski': 'Polish',
    'Português': 'Portuguese',
    'ਪੰਜਾਬੀ': 'Punjabi',
    'Runa Simi': 'Quechua',
    'राजस्थानी': 'Rajasthani',
    'Ruáinga': 'Rohingya',
    'Romani': 'Romani',
    'Română': 'Romanian',
    'Rumantsch': 'Romansh',
    'Русский': 'Russian',
    'Gagana Samoa': 'Samoan',
    'Sängö': 'Sango',
    'संस्कृतम्': 'Sanskrit',
    'संथाली': 'Santali',
    'Sardu': 'Sardinian',
    'Scots': 'Scots',
    'Српски': 'Serbian',
    'Sesotho': 'Sesotho',
    'ၵႂၢမ်းတႆး': 'Shan',
    'chiShona': 'Shona',
    'Sicilianu': 'Sicilian',
    'Ślōnskŏ gŏdka': 'Silesian',
    'سنڌي': 'Sindhi',
    'සිංහල': 'Sinhala',
    'Slovenčina': 'Slovak',
    'Slovenščina': 'Slovenian',
    'Af-Soomaali': 'Somali',
    'Soninke': 'Soninke',
    'سۆرانی': 'Sorani',
    'Español': 'Spanish',
    'Basa Sunda': 'Sundanese',
    'Kiswahili': 'Swahili',
    'SiSwati': 'Swati',
    'Svenska': 'Swedish',
    'ꠍꠤꠟꠐꠤ': 'Sylheti',
    'Tagalog': 'Tagalog',
    'Reo Tahiti': 'Tahitian',
    'Тоҷикӣ': 'Tajik',
    'தமிழ்': 'Tamil',
    'Татарча': 'Tatar',
    'తెలుగు': 'Telugu',
    'Tetun': 'Tetum',
    'ไทย': 'Thai',
    'བོད་ཡིག': 'Tibetan',
    'ትግርኛ': 'Tigrinya',
    'Lea faka-Tonga': 'Tongan',
    'Xitsonga': 'Tsonga',
    'Setswana': 'Tswana',
    'chiTumbuka': 'Tumbuka',
    'Türkçe': 'Turkish',
    'Türkmençe': 'Turkmen',
    'Te gana Tuvalu': 'Tuvalu',
    'Twi': 'Twi',
    'Удмурт': 'Udmurt',
    'Українська': 'Ukrainian',
    'اردو': 'Urdu',
    'ئۇيغۇرچە': 'Uyghur',
    "O'zbek": 'Uzbek',
    'Valencià': 'Valencian',
    'Tshivenḓa': 'Venda',
    'Vèneto': 'Venetian',
    'Tiếng Việt': 'Vietnamese',
    'Winaray': 'Waray',
    'Cymraeg': 'Welsh',
    'Wolof': 'Wolof',
    '吳語': 'Wu',
    'isiXhosa': 'Xhosa',
    '湘語': 'Xiang',
    'Саха тыла': 'Yakut',
    'Chiyao': 'Yao',
    'ייִדיש': 'Yiddish',
    'Yorùbá': 'Yoruba',
    "Yucatec Maaya T'aan": 'Yucatec Maya',
    'Diidxazá': 'Zapotec',
    'Vahcuengh': 'Zhuang',
    'isiZulu': 'Zulu',
} as const;

const mapLanguageToNative = (name: LanguageName): LanguageNativeName => LANGUAGES_TO_NATIVES[name];

const mapNativeToLanguages = (name: LanguageNativeName): LanguageName => NATIVES_TO_LANGUAGES[name];

export default {
    LANGUAGES_TO_NATIVES,
    NATIVES_TO_LANGUAGES,
    mapLanguageToNative,
    mapNativeToLanguages,
};
