import Language, { LanguageName, LanguageNativeName } from '.';
import Names from './names';
import NativeNames from './nativeNames';

const {
    LANGUAGES,
    LANGUAGES_NATIVES,
    LANGUAGES_TO_NATIVES,
    NATIVES_TO_LANGUAGES,
    mapLanguageToNative, 
    mapNativeToLanguages
} = Language;

const NUMBER_OF_LANGUAGES = 232;
const LANGUAGE_KEYS = [...Object.keys(Names)] as const;
const LANGUAGE_NATIVE_KEYS = [...Object.keys(NativeNames)] as const;

const mappingTestCases = [
    ['Acehnese', 'Bahsa Acèh'],
    ['Afrikaans', 'Afrikaans'],
    ['Akan', 'Akan'],
    ['Albanian', 'Shqip'],
    ['Amharic', 'አማርኛ'],
    ['Arabic', 'العربية'],
    ['Armenian', 'Հայերեն'],
    ['Assamese', 'অসমীয়া'],
    ['Awadhi', 'अवधी'],
    ['Aymara', 'Aymar aru'],
    ['Azerbaijani', 'Azərbaycan'],
    ['Balinese', 'Basa Bali'],
    ['Balochi', 'بلوچی'],
    ['Bambara', 'Bamanankan'],
    ['Banjar', 'Bahasa Banjar'],
    ['Bashkir', 'Башҡорт теле'],
    ['Basque', 'Euskara'],
    ['Batak', 'Hata Batak'],
    ['Belarusian', 'Беларуская'],
    ['Bemba', 'Ichibemba'],
    ['Bengali', 'বাংলা'],
    ['Bhojpuri', 'भोजपुरी'],
    ['Bikol', 'Bikol'],
    ['Bosnian', 'Bosanski'],
    ['Breton', 'Brezhoneg'],
    ['Buginese', 'Basa Ugi'],
    ['Bulgarian', 'Български'],
    ['Burmese', 'မြန်မာဘာသာ'],
    ['Cantonese', '粵語'],
    ['Catalan', 'Català'],
    ['Cebuano', 'Sinugbuanong Binisaya'],
    ['Chhattisgarhi', 'छत्तिसगढ़ी'],
    ['Chewa', 'Chichewa'],
    ['Chinese', '中文'],
    ['Chittagonian', 'চাটগাঁইয়া'],
    ['Chuvash', 'Чӑваш чӗлхи'],
    ['Corsican', 'Corsu'],
    ['Cree', 'Nēhiyawēwin'],
    ['Croatian', 'Hrvatski'],
    ['Czech', 'Čeština'],
    ['Danish', 'Dansk'],
    ['Dari', 'دری'],
    ['Dholuo', 'Dholuo'],
    ['Dutch', 'Nederlands'],
    ['Dzongkha', 'རྫོང་ཁ'],
    ['English', 'English'],
    ['Esperanto', 'Esperanto'],
    ['Estonian', 'Eesti'],
    ['Ewe', 'Eʋegbe'],
    ['Faroese', 'Føroyskt'],
    ['Fijian', 'Na Vosa Vakaviti'],
    ['Filipino', 'Filipino'],
    ['Finnish', 'Suomi'],
    ['French', 'Français'],
    ['Frisian', 'Frysk'],
    ['Fulani', 'Fulfulde'],
    ['Ga', 'Ga'],
    ['Galician', 'Galego'],
    ['Gan', '贛語'],
    ['Garhwali', 'गढ़वाली'],
    ['Georgian', 'ქართული'],
    ['German', 'Deutsch'],
    ['Gondi', 'Gondi'],
    ['Greek', 'Ελληνικά'],
    ['Guarani', "Avañe'ẽ"],
    ['Gujarati', 'ગુજરાતી'],
    ['Haitian Creole', 'Kreyòl ayisyen'],
    ['Hakka', '客家話'],
    ['Haryanvi', 'हरियाणवी'],
    ['Hausa', 'Hausa'],
    ['Hawaiian', "ʻŌlelo Hawaiʻi"],
    ['Hebrew', 'עברית'],
    ['Hiligaynon', 'Hiligaynon'],
    ['Hindi', 'हिन्दी'],
    ['Hmong', 'Hmoob'],
    ['Hungarian', 'Magyar'],
    ['Icelandic', 'Íslenska'],
    ['Igbo', 'Igbo'],
    ['Ilocano', 'Ilokano'],
    ['Indonesian', 'Bahasa Indonesia'],
    ['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'],
    ['Irish', 'Gaeilge'],
    ['Italian', 'Italiano'],
    ['Japanese', '日本語'],
    ['Javanese', 'Basa Jawa'],
    ['Kabyle', 'Taqbaylit'],
    ['Kamba', 'Kikamba'],
    ['Kannada', 'ಕನ್ನಡ'],
    ['Kanuri', 'Kanuri'],
    ['Kapampangan', 'Kapampangan'],
    ['Karen', 'ကညီကျိာ်'],
    ['Kashmiri', 'कश्मीरी'],
    ['Kashubian', 'Kaszëbsczi'],
    ['Kazakh', 'Қазақ тілі'],
    ['Khmer', 'ភាសាខ្មែរ'],
    ['Kikuyu', 'Gĩkũyũ'],
    ['Kinyarwanda', 'Ikinyarwanda'],
    ['Kirundi', 'Ikirundi'],
    ['Komi', 'Коми кыв'],
    ['Konkani', 'कोंकणी'],
    ['Korean', '한국어'],
    ['Kurdish', 'Kurdî'],
    ['Kurmanji', 'Kurmancî'],
    ['Kyrgyz', 'Кыргызча'],
    ['Lao', 'ພາສາລາວ'],
    ['Latin', 'Latina'],
    ['Latvian', 'Latviešu'],
    ['Ligurian', 'Ligure'],
    ['Limburgish', 'Limburgs'],
    ['Lingala', 'Lingála'],
    ['Lithuanian', 'Lietuvių'],
    ['Lombard', 'Lombard'],
    ['Luba-Kasai', 'Tshiluba'],
    ['Luganda', 'Luganda'],
    ['Luo', 'Luo'],
    ['Luxembourgish', 'Lëtzebuergesch'],
    ['Macedonian', 'Македонски'],
    ['Madurese', 'Basa Madura'],
    ['Magahi', 'मगही'],
    ['Maithili', 'मैथिली'],
    ['Makassar', 'Basa Mangkasara'],
    ['Malagasy', 'Malagasy'],
    ['Malay', 'Bahasa Melayu'],
    ['Malayalam', 'മലയാളം'],
    ['Maltese', 'Malti'],
    ['Mandarin', '官話'],
    ['Manipuri', 'মনিপুরি'],
    ['Maori', 'Te Reo Māori'],
    ['Mapudungun', 'Mapudungun'],
    ['Maranao', 'Mëranaw'],
    ['Marathi', 'मराठी'],
    ['Marwari', 'मारवाड़ी'],
    ['Maya', "Maaya T'aan"],
    ['Meitei', 'ꯃꯩꯇꯩꯂꯣꯟ'],
    ['Meru', 'Kĩmĩrũ'],
    ['Min Nan', '閩南語'],
    ['Minangkabau', 'Baso Minangkabau'],
    ['Mirandese', 'Mirandés'],
    ['Mixtec', "Tu'un savi"],
    ['Mon', 'ဘာသာ မန်'],
    ['Mongolian', 'Монгол'],
    ['Montenegrin', 'Crnogorski'],
    ['Mossi', 'Mòoré'],
    ['Nahuatl', 'Nāhuatl'],
    ['Navajo', 'Diné bizaad'],
    ['Nepali', 'नेपाली'],
    ['Newar', 'नेपाल भाषा'],
    ['Norwegian', 'Norsk'],
    ['Nyanja', 'Chinyanja'],
    ['Occitan', 'Occitan'],
    ['Odia', 'ଓଡ଼ିଆ'],
    ['Ojibwe', 'Anishinaabemowin'],
    ['Oromo', 'Afaan Oromoo'],
    ['Pangasinan', 'Pangasinan'],
    ['Pashto', 'پښتو'],
    ['Persian', 'فارسی'],
    ['Polish', 'Polski'],
    ['Portuguese', 'Português'],
    ['Punjabi', 'ਪੰਜਾਬੀ'],
    ['Quechua', 'Runa Simi'],
    ['Rajasthani', 'राजस्थानी'],
    ['Rohingya', 'Ruáinga'],
    ['Romani', 'Romani'],
    ['Romanian', 'Română'],
    ['Romansh', 'Rumantsch'],
    ['Russian', 'Русский'],
    ['Samoan', 'Gagana Samoa'],
    ['Sango', 'Sängö'],
    ['Sanskrit', 'संस्कृतम्'],
    ['Santali', 'संथाली'],
    ['Sardinian', 'Sardu'],
    ['Scots', 'Scots'],
    ['Serbian', 'Српски'],
    ['Sesotho', 'Sesotho'],
    ['Shan', 'ၵႂၢမ်းတႆး'],
    ['Shona', 'chiShona'],
    ['Sicilian', 'Sicilianu'],
    ['Silesian', 'Ślōnskŏ gŏdka'],
    ['Sindhi', 'سنڌي'],
    ['Sinhala', 'සිංහල'],
    ['Slovak', 'Slovenčina'],
    ['Slovenian', 'Slovenščina'],
    ['Somali', 'Af-Soomaali'],
    ['Soninke', 'Soninke'],
    ['Sorani', 'سۆرانی'],
    ['Spanish', 'Español'],
    ['Sundanese', 'Basa Sunda'],
    ['Swahili', 'Kiswahili'],
    ['Swati', 'SiSwati'],
    ['Swedish', 'Svenska'],
    ['Sylheti', 'ꠍꠤꠟꠐꠤ'],
    ['Tagalog', 'Tagalog'],
    ['Tahitian', 'Reo Tahiti'],
    ['Tajik', 'Тоҷикӣ'],
    ['Tamil', 'தமிழ்'],
    ['Tatar', 'Татарча'],
    ['Telugu', 'తెలుగు'],
    ['Tetum', 'Tetun'],
    ['Thai', 'ไทย'],
    ['Tibetan', 'བོད་ཡིག'],
    ['Tigrinya', 'ትግርኛ'],
    ['Tongan', 'Lea faka-Tonga'],
    ['Tsonga', 'Xitsonga'],
    ['Tswana', 'Setswana'],
    ['Tumbuka', 'chiTumbuka'],
    ['Turkish', 'Türkçe'],
    ['Turkmen', 'Türkmençe'],
    ['Tuvalu', 'Te gana Tuvalu'],
    ['Twi', 'Twi'],
    ['Udmurt', 'Удмурт'],
    ['Ukrainian', 'Українська'],
    ['Urdu', 'اردو'],
    ['Uyghur', 'ئۇيغۇرچە'],
    ['Uzbek', "O'zbek"],
    ['Valencian', 'Valencià'],
    ['Venda', 'Tshivenḓa'],
    ['Venetian', 'Vèneto'],
    ['Vietnamese', 'Tiếng Việt'],
    ['Waray', 'Winaray'],
    ['Welsh', 'Cymraeg'],
    ['Wolof', 'Wolof'],
    ['Wu', '吳語'],
    ['Xhosa', 'isiXhosa'],
    ['Xiang', '湘語'],
    ['Yakut', 'Саха тыла'],
    ['Yao', 'Chiyao'],
    ['Yiddish', 'ייִדיש'],
    ['Yoruba', 'Yorùbá'],
    ['Yucatec Maya', "Yucatec Maaya T'aan"],
    ['Zapotec', 'Diidxazá'],
    ['Zhuang', 'Vahcuengh'],
    ['Zulu', 'isiZulu'],
] as ([LanguageName, LanguageNativeName])[];

const removeDashesWithSpace = (arr: readonly string[]): string[] =>
    arr.map((arg: string) => arg.replace('_', ' '));

const sortArray = (arr: readonly string[]): string[] =>
    removeDashesWithSpace(arr).sort();

it('should contain all names', () => {
    expect(LANGUAGES).toHaveLength(NUMBER_OF_LANGUAGES);
    expect(LANGUAGES_NATIVES).toHaveLength(NUMBER_OF_LANGUAGES);
    expect((new Set(LANGUAGES)).size).toBe(NUMBER_OF_LANGUAGES);
    expect((new Set(LANGUAGES_NATIVES)).size).toBe(NUMBER_OF_LANGUAGES);
});

it('should be sorted', () => {
    expect(removeDashesWithSpace(LANGUAGE_KEYS)).toEqual(sortArray([...LANGUAGE_KEYS]));
    expect(removeDashesWithSpace(LANGUAGE_NATIVE_KEYS)).toEqual(sortArray([...LANGUAGE_NATIVE_KEYS]));
});

beforeAll(() => {
    expect(mappingTestCases).toHaveLength(NUMBER_OF_LANGUAGES);
});

describe.each(mappingTestCases)('Mapping:', (englishName, nativeName) => {
    it(`should map ${englishName} to ${nativeName} correctly`, () => {
        expect(LANGUAGES_TO_NATIVES[englishName]).toEqual(nativeName);
        expect(mapLanguageToNative(englishName)).toEqual(nativeName);
    });

    it(`should map ${nativeName} to ${englishName} correctly`, () => {
        expect(NATIVES_TO_LANGUAGES[nativeName]).toEqual(englishName);
        expect(mapNativeToLanguages(nativeName)).toEqual(englishName);
    });
});
